server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/equipment_schema?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml